# Generated by Django 5.1.15 on 2026-06-04 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SituationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(verbose_name='情境描述')),
                ('option_a', models.CharField(max_length=100, verbose_name='選項 A')),
                ('option_b', models.CharField(max_length=100, verbose_name='選項 B')),
                ('option_c', models.CharField(max_length=100, verbose_name='選項 C')),
                ('active_date', models.DateField(blank=True, help_text='指定哪天作為當日題目，留空表示備用題庫', null=True, verbose_name='每日顯示日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
            ],
            options={
                'verbose_name': '情境題',
                'verbose_name_plural': '情境題',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SituationResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('text', '簡答'), ('choice', '選擇')], max_length=6, verbose_name='回答模式')),
                ('text_answer', models.TextField(blank=True, max_length=200, verbose_name='簡答內容')),
                ('choice', models.CharField(blank=True, choices=[('a', 'A'), ('b', 'B'), ('c', 'C')], max_length=1, null=True, verbose_name='選擇')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.situationquestion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='situation_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '情境題回答',
                'verbose_name_plural': '情境題回答',
                'ordering': ['-created_at'],
            },
        ),
    ]
