# Generated by Django 5.1.15 on 2026-06-04 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='situationresponse',
            name='is_public',
            field=models.BooleanField(default=True, help_text='關閉後此則簡答不會出現在其他人看到的範例中（僅 mode=text 有效）', verbose_name='公開簡答'),
        ),
    ]
