# Generated by Django 5.1.15 on 2026-06-01 12:41

import django.contrib.auth.models
import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import django_cryptography.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='電子郵件')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '使用者',
                'verbose_name_plural': '使用者',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AISetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gemini_api_key', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=200, verbose_name='Gemini API 金鑰'))),
                ('model_name', models.CharField(blank=True, help_text='留空則使用系統預設', max_length=60, verbose_name='模型')),
                ('key_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='金鑰驗證時間')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_setting', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI 設定',
                'verbose_name_plural': 'AI 設定',
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accent', models.CharField(choices=[('peach', '蜜桃'), ('sage', '鼠尾草綠'), ('sky', '天空藍'), ('lilac', '薰衣草紫')], default='peach', max_length=10, verbose_name='主題色')),
                ('font_scale', models.PositiveSmallIntegerField(default=100, verbose_name='字級 (%)')),
                ('board_react', models.CharField(choices=[('tray', '回應盤'), ('quick', '常駐'), ('words', '暖心語')], default='tray', max_length=10, verbose_name='看板互動模式')),
                ('tree_style', models.CharField(choices=[('tree', '心情樹'), ('garden', '花園'), ('jar', '感謝罐')], default='tree', max_length=10, verbose_name='成長視覺')),
                ('soft_bg', models.BooleanField(default=True, verbose_name='柔光漸層背景')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '使用者偏好',
                'verbose_name_plural': '使用者偏好',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nickname', models.CharField(blank=True, max_length=40, verbose_name='暱稱')),
                ('self_description_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=None, verbose_name='自我描述標籤')),
                ('interested_topics', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=None, verbose_name='關注主題')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=40, verbose_name='緊急聯絡人姓名')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, verbose_name='緊急聯絡人電話')),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=20, verbose_name='關係')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '個人檔案',
                'verbose_name_plural': '個人檔案',
            },
        ),
    ]
