# Generated by Django 5.1.15 on 2026-06-10 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_crisis_until'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AISetting',
        ),
    ]
