# Generated by Django 5.1.15 on 2026-06-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_aisetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='board_react',
            field=models.CharField(choices=[('tray', '回應盤'), ('quick', '常駐')], default='tray', max_length=10, verbose_name='看板互動模式'),
        ),
    ]
