# Generated by Django 5.1.15 on 2026-06-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userpreference_board_react'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='tree_style',
            field=models.CharField(choices=[('tree', '心情樹'), ('garden', '花園'), ('jar', '感謝罐'), ('sky', '星空')], default='tree', max_length=10, verbose_name='成長視覺'),
        ),
    ]
