# Generated by Django 5.1.15 on 2026-06-01 12:41

import django.db.models.deletion
import django_cryptography.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crisis_mode', models.BooleanField(default=False, help_text='True 表示已切換到安全模式 system prompt', verbose_name='危機模式')),
                ('crisis_since', models.DateTimeField(blank=True, null=True, verbose_name='進入危機時間')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='結束時間')),
                ('summary', django_cryptography.fields.encrypt(models.TextField(blank=True, verbose_name='摘要（加密）'))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '對話期間',
                'verbose_name_plural': '對話期間',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender', models.CharField(choices=[('user', '使用者'), ('ai', 'AI')], max_length=4, verbose_name='發送者')),
                ('message_content', django_cryptography.fields.encrypt(models.TextField(verbose_name='內容（加密）'))),
                ('crisis_flagged', models.BooleanField(default=False, verbose_name='危機標記')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='companion.chatsession')),
            ],
            options={
                'verbose_name': '對話記錄',
                'verbose_name_plural': '對話記錄',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SOSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('triggering_keyword', models.CharField(blank=True, max_length=80, verbose_name='觸發關鍵字')),
                ('detector', models.CharField(default='keyword', max_length=20, verbose_name='偵測器')),
                ('action_taken', models.CharField(default='system_prompt_switched+hotlines_surfaced', max_length=120, verbose_name='採取動作')),
                ('chat_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companion.aichatlog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SOS 事件',
                'verbose_name_plural': 'SOS 事件',
                'ordering': ['-created_at'],
            },
        ),
    ]
