# Generated by Django 5.1.15 on 2026-06-10 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companion', '0004_chatsession_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='summary',
        ),
    ]
