# Generated by Django 5.1.15 on 2026-06-11 03:29

import accounts.crypto
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companion', '0005_remove_chatsession_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aichatlog',
            name='message_content',
            field=accounts.crypto.LenientEncryptedTextField(verbose_name='內容'),
        ),
    ]
