# Generated by Django 5.1.15 on 2026-06-01 12:41

import django.db.models.deletion
import django_cryptography.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=60, verbose_name='任務名稱')),
                ('icon', models.CharField(max_length=8, verbose_name='圖示（emoji）')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
            ],
            options={
                'verbose_name': '每日任務',
                'verbose_name_plural': '每日任務',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='KudosNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('praise_content', django_cryptography.fields.encrypt(models.TextField(verbose_name='內容（加密）'))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kudos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '誇誇筆記',
                'verbose_name_plural': '誇誇筆記',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyTaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='日期')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='growth.dailytask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '任務完成記錄',
                'verbose_name_plural': '任務完成記錄',
                'unique_together': {('user', 'task', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(verbose_name='週開始')),
                ('end_date', models.DateField(verbose_name='週結束')),
                ('summary_data', models.JSONField(default=dict, help_text='心情樹/花園/罐視覺化資料與統計', verbose_name='摘要資料')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '每週回顧',
                'verbose_name_plural': '每週回顧',
                'ordering': ['-start_date'],
                'unique_together': {('user', 'start_date')},
            },
        ),
    ]
