# Generated by Django 5.1.15 on 2026-06-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0003_weeklyreviewversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyreviewversion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
