# Generated by Django 5.1.15 on 2026-06-04 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0005_kudosnote_soft_delete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='打卡日期')),
                ('mood', models.CharField(choices=[('awful', '😭 很難過'), ('sad', '😢 有點低落'), ('neutral', '😐 普通'), ('good', '🙂 還不錯'), ('great', '😄 很開心')], max_length=10, verbose_name='心情')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_moods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '每日心情',
                'verbose_name_plural': '每日心情',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
