# Generated by Django 5.1.15 on 2026-06-01 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PresetIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_path', models.CharField(help_text='相對 static/ 的路徑，例如 img/assets/mood-sun.jpg', max_length=200, verbose_name='圖片路徑')),
                ('emotion_type', models.CharField(choices=[('sun', '晴朗'), ('breeze', '微風'), ('rainbow', '雨後彩虹'), ('cloud', '烏雲'), ('rain', '大雨'), ('storm', '閃電')], max_length=20, unique=True, verbose_name='情緒類型')),
                ('label', models.CharField(max_length=20, verbose_name='標籤')),
                ('desc', models.CharField(blank=True, max_length=60, verbose_name='描述')),
                ('tint_var', models.CharField(blank=True, help_text='例如 var(--sage-tint)', max_length=40, verbose_name='色調 CSS 變數')),
                ('ring_var', models.CharField(blank=True, help_text='例如 var(--sage-deep)', max_length=40, verbose_name='邊框 CSS 變數')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
            ],
            options={
                'verbose_name': '預設心情圖示',
                'verbose_name_plural': '預設心情圖示',
                'ordering': ['emotion_type'],
            },
        ),
        migrations.CreateModel(
            name='PresetMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(max_length=60, verbose_name='內容')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
            ],
            options={
                'verbose_name': '暖心語錄',
                'verbose_name_plural': '暖心語錄',
            },
        ),
        migrations.CreateModel(
            name='BoardPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_posts', to=settings.AUTH_USER_MODEL)),
                ('preset_icon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='board.preseticon')),
            ],
            options={
                'verbose_name': '看板貼文',
                'verbose_name_plural': '看板貼文',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BoardReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sticker', models.CharField(choices=[('hug', '抱抱'), ('pat', '拍拍'), ('highfive', '擊掌加油'), ('warm', '暖暖的')], max_length=10, verbose_name='貼圖')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='board.boardpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '看板回應',
                'verbose_name_plural': '看板回應',
                'unique_together': {('post', 'user', 'sticker')},
            },
        ),
    ]
