# Generated by Django 5.1.15 on 2026-06-10 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_boardpost_soft_delete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='boardpost',
            name='is_anonymous',
            field=models.BooleanField(default=True, verbose_name='匿名發布'),
        ),
        migrations.AddField(
            model_name='boardpost',
            name='preset_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='board.presetmessage'),
        ),
        migrations.AlterField(
            model_name='boardpost',
            name='preset_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='board.preseticon'),
        ),
        migrations.AddConstraint(
            model_name='boardpost',
            constraint=models.CheckConstraint(condition=models.Q(('preset_icon__isnull', False), ('preset_message__isnull', False), _connector='OR'), name='board_post_icon_or_message_required'),
        ),
    ]
