# Generated by Django 5.1.15 on 2026-06-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_boardpost_is_anonymous_boardpost_preset_message_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presetmessage',
            options={'ordering': ['category', 'content'], 'verbose_name': '暖心語錄', 'verbose_name_plural': '暖心語錄'},
        ),
        migrations.AddField(
            model_name='presetmessage',
            name='category',
            field=models.CharField(choices=[('self_encourage', '自我鼓勵'), ('companionship', '陪伴支持'), ('self_acceptance', '接納自己'), ('facing_setbacks', '面對挫折'), ('hope_future', '希望與未來'), ('gratitude', '感恩珍惜'), ('stress_relief', '壓力舒緩'), ('relationships', '人際關係'), ('courage_growth', '勇氣成長'), ('depression_relief', '憂鬱與低潮療癒')], default='self_encourage', max_length=20, verbose_name='分類'),
        ),
    ]
