# Generated by Django 5.1.15 on 2026-06-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='診所名稱')),
                ('clinic_type', models.CharField(choices=[('諮商所', '諮商所'), ('身心科', '身心科')], db_index=True, max_length=10, verbose_name='類型')),
                ('county', models.CharField(db_index=True, max_length=10, verbose_name='縣市')),
                ('district', models.CharField(max_length=20, verbose_name='行政區')),
                ('address', models.CharField(blank=True, max_length=120, verbose_name='地址')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
            ],
            options={
                'verbose_name': '診所',
                'verbose_name_plural': '診所',
                'ordering': ['county', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PsychoArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120, verbose_name='標題')),
                ('category', models.CharField(choices=[('壓力管理', '壓力管理'), ('情緒覺察', '情緒覺察'), ('焦慮', '焦慮'), ('睡眠', '睡眠'), ('人際關係', '人際關係'), ('自我照顧', '自我照顧')], db_index=True, max_length=20, verbose_name='分類')),
                ('read_minutes', models.PositiveSmallIntegerField(default=4, verbose_name='閱讀分鐘')),
                ('excerpt', models.TextField(verbose_name='摘要')),
                ('content_markdown', models.TextField(blank=True, verbose_name='正文（Markdown）')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
            ],
            options={
                'verbose_name': '心理科普文章',
                'verbose_name_plural': '心理科普文章',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PsychoPodcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, verbose_name='Podcast 名稱')),
                ('url', models.URLField(verbose_name='連結')),
                ('desc', models.CharField(blank=True, max_length=120, verbose_name='說明')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
            ],
            options={
                'verbose_name': '心理 Podcast',
                'verbose_name_plural': '心理 Podcast',
            },
        ),
        migrations.CreateModel(
            name='PsychoScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='量表名稱')),
                ('org', models.CharField(max_length=80, verbose_name='提供機構')),
                ('external_url', models.URLField(verbose_name='外部連結')),
                ('note', models.TextField(blank=True, verbose_name='說明')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
            ],
            options={
                'verbose_name': '心理量表',
                'verbose_name_plural': '心理量表',
            },
        ),
        migrations.CreateModel(
            name='PsychoVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, verbose_name='頻道/影片名稱')),
                ('lang', models.CharField(default='中文', max_length=10, verbose_name='語言')),
                ('url', models.URLField(verbose_name='連結')),
                ('desc', models.CharField(blank=True, max_length=120, verbose_name='說明')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
            ],
            options={
                'verbose_name': '心理影片',
                'verbose_name_plural': '心理影片',
            },
        ),
    ]
