# Generated by Django 5.1.15 on 2026-06-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_psychoarticle_category_maxlength'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='website_url',
            field=models.URLField(blank=True, verbose_name='官網'),
        ),
    ]
